### ISSUE TITLE
Add embedding for media

### ISSUE THREAD

**Issue by enoxitus** [szabodanika/microbin#139]
It would be really cool if I could upload an image or video, post the link somewhere and have it embed it automatically e.g on discord.
This works if I copy the link to the exact file, but then depending on the file name this can be a large URL. 

Example:
- https://url.com/monkey-dog-fox has an image attached, the image is automatically embedded on discord. 

To achieve this currently, it would look like:
- https://url.com/monkey-dog-fox/P_20230126_123935038.jpg

Hopefully it's understandable what I meant!

**Comment by szabodanika** [comment]
This would really be useful as I myself use MicroBin over Discord a lot. The issue is that Discord uses a bot to visit the URL and takes the first image. Because there is no image displayed at https://url.com/monkey-dog-fox, it has nothing to show in the chat. What we could easily do is displaying image and video files on the pasta page instead of just making them downloadable, this would make MicroBin itself more user friendly, and it would help in use cases like this one as well.

**Comment by szabodanika** [comment]
Related: #58

**Comment by flamion** [comment]
I think it would be enough to set a few fields in the HTML header. There are fields that tell crawlers what to embed. A website for generating links that do something similar is stolen.shoes, if the link is pasted into discord or some other platform that looks for these fields it will embed the resource properly, but with stolen.shoes if the link is opened in the browser it will display something else (like the normal site).
![image](https://user-images.githubusercontent.com/57202317/231883992-2b2c05f4-506a-4673-9af7-58da1b145180.png)

[Example link](https://stolen.shoes/embedVideo/?video=https://minio.dragoncave.dev/flam-testing/c427ec775a8bff87.mp4&image=https://www.danthermgroup.com/media/products/Master-Stainless-steel-exhaust-pipe-4013.260.jpg?v=1638782876)

**Comment by iraizo** [comment]
I don't think its a good idea to rely on bots scraping the site contents due to two main reasons:
1. the difference in crawlers
2. [OGP](https://ogp.me/) is basically THE standard on how to do this

HTTP GET `instance.com/file/XXXX` returns `Content-Type: image/jpeg;` while HTTP HEAD returns the type as `text/html`.
when doing GET/HEAD of the `instance.com/p/XXXX` url, both return text/html.

Doing some quick testing these were my results

**Signal**:
  -  `instance.com/p/XXXX`: Only embeds the microbin logo/favicon (?)
  - `instance.com/file/XXXX` Does not embed (`Content-Disposition: attachment`)
  - `instance.com/file/XXXX?preview=true` Embeds the correct image (`Content-Disposition: inline`)  
  Both `*/file/*` routes return the correct `Content-Type` header.

**Discord**:
Fails to embed anything tested above.

**Comment by iraizo** [comment]
Shouldn't this be open again?

**Comment by iraizo** [comment]
CC @szabodanika
