### ISSUE TITLE
Unable to save anything when click the save button

### ISSUE THREAD

**Issue by dfmjndm** [szabodanika/microbin#200]
![image](https://github.com/szabodanika/microbin/assets/57401901/ef857d2f-6b8e-4ac2-a812-b0e69fcceca8)
I used docker version

**Comment by szabodanika** [comment]
Hi there, please have a look at #180, you are experiencing the same error. I recommend configuring MicroBin with a .env file or setting environmental variables in some other way, you are currently running it without any configuration which is also a security issue (you are using default admin login for example). Regardless, this is a bug and will be fixed so that MicroBin works without any configuration whatsoever.
