### ISSUE TITLE
auth form is not readable with dark theme

### ISSUE THREAD

**Issue by foozzi** [szabodanika/microbin#232]
microbin: 2.0.4
<img width="623" alt="Снимок экрана 2023-10-14 в 11 35 16" src="https://github.com/szabodanika/microbin/assets/1178208/7050791e-01e4-4b09-90b9-85abcbbda497">

**Comment by Skaronator** [comment]
Just run into the same issue.

The reason is that the CSS doesn't have any logic for dark mode:

https://github.com/szabodanika/microbin/blob/b8a0c5490d681550d982ad02d67a1aaa0897f503/templates/auth_admin.html#L19

https://github.com/szabodanika/microbin/blob/b8a0c5490d681550d982ad02d67a1aaa0897f503/templates/auth_upload.html#L110

/cc @szabodanika
