### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [szabodanika/microbin#32]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ablgh) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by dvdsk** [comment]
It would be great (though probably overkill) if you could provide us with your *public pgp key* that way we can safely disclose information to you even over insecure channels such as email.

A question for @JamieSlome, if I where to find an issue and solve it how can I contribute the fix safely? Lets assume the fix makes this issue obvious. Do we coordinate putting up the pull request and merging? Should I send a pgp encrypted patch file? Maybe work on a private fork? Feel free to drop a link to a good resource on this instead of writing up a comment.

**Comment by szabodanika** [comment]
Hello and Thanks for reaching out @JamieSlome, I'd be very grateful to hear about the issue you discovered. @dvdsk has shared something with me, I'm curious about whether you two found the same issue. Feel free to drop an email to d@szab.eu (should be able to use this GPG key, never tried GPG mailing before: https://keys.openpgp.org/vks/v1/by-fingerprint/CDB715C08F9370134E030AE1D4D95121C054CFBC), I will create a security policy ASAP as well.

**Comment by JamieSlome** [comment]
@szabodanika - thanks for your response 👍 

I sent over the first of two reports to the e-mail address you mentioned above :)
